import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TonProvider from "@/ton/TonProvidor";
import ModalProvider from "@/components/modals/ModalProvider";
import Header from "@/components/mains/Header";
import Footer from "@/components/mains/Footer";


const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
         >
               <TonProvider>
                  <span className="text-orange-500 text-blue-500 text-green-500 bg-blue-500/50"></span>
                  <ModalProvider />
                  <Header />
                  {children}
                  <Footer />
               </TonProvider>
            
         </body>
      </html>
   );
}
